:abbr #i #include<
:abbr #d #define
:abbr cl class
:abbr wh while
:abbr fr for
:abbr in int
:abbr fl float
:abbr lo long
:abbr do double
:abbr ch char
:abbr st string
:abbr re return
:abbr tr try
:abbr ca catch
:abbr st static
:abbr lo long
:abbr cl class
:abbr pr private
:abbr pu public
:abbr pro protected
:abbr io iostream
:abbr ma main()
:abbr [[ [][]
:abbr br break;
:abbr NL NULL
:abbr el else
:abbr c< cout<<
:abbr en <<endl;
:abbr c> cin>>
:abbr vo void
