:abbr pr print
:abbr im import
:abbr de def
:abbr wh while
:abbr fo for
:abbr la lamda
:abbr ra range(
:abbr cl class
:abbr br break
:abbr con continue
:abbr el else
:abbr li list(
:abbr lr list(range(
:abbr fr from
:abbr gl global
:abbr inp input(
:abbr raw raw_input(
:abbr re return
:abbr wr write
:abbr sp split
:abbr tr True
:abbr fa False
:abbr hw "Hello World"
:abbr tr try
:abbr se self
:abbr ca catch
:abbr ex except
:abbr __ __init__(self):
